# (실습) 어레이 변형

In [3]:
import numpy as np

**문제 1**

아래 모양의 어레이를 생성하라.
단, `np.arange()` 함수와 `reshape()` 어레이 메서드를 이용한다.

```python
array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])
```

In [8]:
Z = np.arange(1,40,2).reshape(4,5)
Z

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

아래 코드는 수정하지 마세요!!!

In [9]:
assert (Z == np.array([[ 1,  3,  5,  7,  9],
                        [11, 13, 15, 17, 19],
                        [21, 23, 25, 27, 29],
                        [31, 33, 35, 37, 39]])).all()

**문제 2**

아래 그림 내용을 코드로 구현하라.

<div align="center"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/concatenate01.png?raw=true" style="width:500px;"></div>

<p><div style="text-align: center">&lt;그림 출처: <a href="https://stackoverflow.com/questions/33356442/when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack">stackoverflow</a>&gt;</div></p>

In [22]:
a = np.arange(1, 13).reshape(3, 4)
b = np.arange(1, 9).reshape(2, 4)
c = np.arange(1, 7).reshape(3, 2)

In [21]:
V = np.vstack((a,b))  # vstack 활용
V

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [16]:
H = np.hstack((a,c))  # hstack 활용
H

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

아래 코드는 수정하지 마세요!!!

In [17]:
assert (V == np.array([[ 1,  2,  3,  4],
                        [ 5,  6,  7,  8],
                        [ 9, 10, 11, 12],
                        [ 1,  2,  3,  4],
                        [ 5,  6,  7,  8]])).all()

assert (H == np.array([[ 1,  2,  3,  4,  1,  2],
                        [ 5,  6,  7,  8,  3,  4],
                        [ 9, 10, 11, 12,  5,  6]])).all()

**문제 3**

이전 문제에서 정의된 `V`, `H`를 `concatenate()` 함수를 이용하여 정의하라.

In [25]:
V = np.concatenate((a,b),axis = 0)
V

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [26]:
H = np.concatenate((a,c),axis = 1)
H

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

아래 코드는 수정하지 마세요!!!

In [27]:
assert (V == np.array([[ 1,  2,  3,  4],
                        [ 5,  6,  7,  8],
                        [ 9, 10, 11, 12],
                        [ 1,  2,  3,  4],
                        [ 5,  6,  7,  8]])).all()

assert (H == np.array([[ 1,  2,  3,  4,  1,  2],
                        [ 5,  6,  7,  8,  3,  4],
                        [ 9, 10, 11, 12,  5,  6]])).all()

**문제 4**

아래 모양의 어레이를 생성하는 코드를 완성하라.
단, `np.newaxis` 키워드를 이용한다.

```python
array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])
```

In [55]:
a = np.arange(0, 31, 10)
b = np.array([0]*3)

Z =a[:,np.newaxis] + b
Z

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

아래 코드는 수정하지 마세요!!!

In [56]:
assert (Z == np.array([[ 0,  0,  0],
                        [10, 10, 10],
                        [20, 20, 20],
                        [30, 30, 30]])).all()

**문제 5**

아래 모양의 어레이를 생성하는 코드를 완성하라.
단, `np.newaxis` 키워드를 이용한다.

```python
array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])
```

In [76]:
a = np.arange(0, 31, 10)
print(a)
b = np.arange(1, 4)
print(b)
Z = a[:, np.newaxis] + b
print(Z)

[ 0 10 20 30]
[1 2 3]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


아래 코드는 수정하지 마세요!!!

In [65]:
assert (Z == np.array([[ 1,  2,  3],
                        [11, 12, 13],
                        [21, 22, 23],
                        [31, 32, 33]])).all()

**문제 6**

어레이가 다음과 같이 주어졌다.

In [66]:
a = np.array([[0.8, 2.9, 3.9],
              [52.4, 23.6, 36.5],
              [55.2, 31.7, 23.9],
              [14.4, 11, 4.9]])

0번 열은 2배, 1번 열은 3배, 2번 열은 8배를 적용하는 코드를 완성하라.

In [67]:
b = np.array([2, 3, 8])
Z = a * b
Z

array([[  1.6,   8.7,  31.2],
       [104.8,  70.8, 292. ],
       [110.4,  95.1, 191.2],
       [ 28.8,  33. ,  39.2]])

아래 코드는 수정하지 마세요!!!

In [68]:
assert np.allclose(Z, np.array([[  1.6,   8.7,  31.2],
                                 [104.8,  70.8, 292. ],
                                 [110.4,  95.1, 191.2],
                                 [ 28.8,  33. ,  39.2]]))

**문제 7**

2차원 어레이 `X`가 다음과 같이 주어졌다.

In [69]:
X = np.array([[58, 68, 54, 21, 13, 97, 33],
              [60, 49, 12, 88, 50, 43, 99],
              [80, 46, 51,  7, 32, 85,  4],
              [93, 18, 86, 79, 17, 16, 59],
              [88, 88, 62, 98, 86, 45, 33]])

(1) 행렬의 각 행의 평균값으로 이루어진 (5, 1) 모양의 2차원 어레이 `X_mean_1`을 생성하라.
단, 소수점 이하는 버리는 `np.int32` dtype을 사용한다.
또한 `mean()` 메서드, `axis`와 `keepdims` 키워드 인자, `astype()` 메서드를 이용한다.

In [79]:
X_mean_1 = X.mean(axis=1, keepdims=True).astype(np.int32)
print(X_mean_1)

[[49]
 [57]
 [43]
 [52]
 [71]]


아래 코드는 수정하지 마세요!!!

In [80]:
assert (X_mean_1 == np.array([[49], [57], [43], [52], [71]])).all()

(2) `X`의 항목과 각 행별 평균값의 차이로 이루어진 (5, 7) 모양의 2차원 어레이를 변수 `Z` 가 가리키도록 하라.

In [82]:
Z = X - X_mean_1
Z

array([[  9,  19,   5, -28, -36,  48, -16],
       [  3,  -8, -45,  31,  -7, -14,  42],
       [ 37,   3,   8, -36, -11,  42, -39],
       [ 41, -34,  34,  27, -35, -36,   7],
       [ 17,  17,  -9,  27,  15, -26, -38]])

아래 코드는 수정하지 마세요!!!

In [83]:
assert (Z == np.array([[  9,  19,   5, -28, -36,  48, -16],
                        [  3,  -8, -45,  31,  -7, -14,  42],
                        [ 37,   3,   8, -36, -11,  42, -39],
                        [ 41, -34,  34,  27, -35, -36,   7],
                        [ 17,  17,  -9,  27,  15, -26, -38]])).all()

**문제 8**

(1) 아래 어레이를 표준화하라.
즉, 항목들의 평균값은 0, 표준편차는 1이 되도록 한다.
단, `mean()` 메서드와 `std()` 메서드를 이용한다.

In [84]:
X = np.random.rand(4, 3)
X

array([[0.22385946, 0.56354753, 0.48523886],
       [0.27886698, 0.36957149, 0.58700412],
       [0.74581586, 0.83014365, 0.88930397],
       [0.12441942, 0.18453349, 0.31798691]])

In [87]:
mean = X.mean()
print(mean)
std_var = X.std()
print(std_var)

#mean = np.mean(X)
#std_var = np.std(X)

Z = (X - mean)/std_var
Z

0.4666909781508124
0.24754856674741388


array([[-0.98094496,  0.39126282,  0.07492621],
       [-0.75873595, -0.39232499,  0.48601834],
       [ 1.12755603,  1.46820754,  1.70719225],
       [-1.38264406, -1.13980659, -0.60070664]])

아래 코드는 수정하지 마세요!!!

In [88]:
assert (round(Z.mean(), 2) == 0.0)
assert (round(Z.std(), 1) == 1.)

(2) `X`를 행 별로 표준화하라.
즉, 각 행의 평균값은 0, 표준편차는 1이 되도록 한다.

In [91]:
row_means = X.mean(axis = 1)
print(row_means)

row_stds = X.std(axis = 1)
print(row_stds)

Z = (X - row_means[:, np.newaxis]) / row_stds[:, np.newaxis]
print(Z)

[0.42421528 0.4118142  0.82175449 0.20897994]
[0.14523522 0.12929413 0.05887837 0.08089217]
[[-1.37952641  0.95935578  0.42017063]
 [-1.02825405 -0.32671791  1.35497196]
 [-1.28975444  0.14248283  1.1472716 ]
 [-1.04534862 -0.30221035  1.34755897]]


아래 코드는 수정하지 마세요!!!

In [92]:
assert (np.round(Z.mean(axis=1), 1) == 0.).all()
assert (np.round(Z.std(axis=1), 1) == 1.).all()